CREATE TABLE InfSec_DMARC.dbo.records
(id bigint IDENTITY (1,1) NOT NULL,
org_name text,
email text,
contact_info text,
date_range_begin bigint,
date_range_end bigint,
domain text,
adkim text,
aspf text,
p text,
pct int,
location text,
source_ip varchar(52) NOT NULL,
"count" int,
disposition text,
dkim text,
spf text,
reason_type text,
comment text,
envelope_to text,
header_from text,
dkim_domain text,
dkim_result text,
dkim_hresult text,
spf_domain text,
spf_result text,
hostname text,
PRIMARY KEY (id))